### ISSUE TITLE
[Data Clean][SVM]預測值筆數有少

### ISSUE THREAD

**Issue by danahuang** [rladiestaipei/GoKaggleUsedCar#10]
以SVM做預測時
很容易會有出來筆數和test data筆數不合的情況

我想應和資料清理建模時有關，似乎也是SVM才會發生的情況?
[kaggle_fullv2.txt](https://github.com/rladiestaipei/GoKaggleUsedCar/files/1133521/kaggle_fullv2.txt)

**Comment by danahuang** [comment]
SVM方法相關的介紹(裡面很多連結都是SVM相關主題，好數學@@)
https://read01.com/Jx4mA8.html
英文版的介紹
http://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation

根據研究所學習作業研究規劃問題的經驗
蠻可能是資料不夠乾淨或是筆數過多時候
易有演算法內計算時 無可行解或是非唯一解等的問題

會再嘗試用本主題的模型多做幾個實驗看看XD

**Comment by githubningyuan** [comment]
是否可以看看是哪些輸入無法順利產出輸出呢？
例如丟1000筆進去作預測，只有900筆結果，
那就把前500筆輸入再丟進去，看看有多少輸出。
重複這步驟，應該可以先抓出10筆以內有問題的輸入，
或許看看這些輸入怎麼了？

**Comment by ClayLu** [comment]
餵給SVM的資料集只有當初建模用的哪些變數嗎? 資料有清理過，沒有NA?  我記得原始資料有幾筆是放錯欄位的，會不會吃到怪東西它就會拉肚子(出來筆數變少)

**Comment by danahuang** [comment]
的確，sum(is.na(data名稱)) 若等於0 <即沒任何缺失資料，我用sample code去稍微改寫成自己的>
跑出來的svm預測就不會有少了

但我看sample code和Wush大大的code並沒看到做清理資料的程序，這部分我再繼續釐清

另外，用data.table::fread來讀資料，那五筆就不會歪掉了喔

我目前跑的code如附件，下面這一段是讓資料沒有缺失值的關鍵，我以為會用差補法等方式讓資料無NA值，這部分我會再往下看
automodel = data.frame(price=auto1$price,stpowerPS,stkilometer,stad_exist_time,
vehicleType=auto1$vehicleType,gearbox=auto1$gearbox,
fuelType=auto1$fuelType,styears,notRepairedDamage=auto1$notRepairedDamage,
brand = auto1$brand)

[sample code dana.txt](https://github.com/rladiestaipei/GoKaggleUsedCar/files/1185711/sample.code.dana.txt)

**Comment by danahuang** [comment]
我目前跑的code如附件，下面這一段是讓資料沒有缺失值的關鍵，我以為會用差補法等方式讓資料無NA值，這部分我會再往下看
automodel = data.frame(price=auto1$price,stpowerPS,stkilometer,stad_exist_time,
                       vehicleType=auto1$vehicleType,gearbox=auto1$gearbox,
                       fuelType=auto1$fuelType,styears,notRepairedDamage=auto1$notRepairedDamage,
                       brand = auto1$brand)
[sample code dana.txt](https://github.com/rladiestaipei/GoKaggleUsedCar/files/1185709/sample.code.dana.txt)

**Comment by danahuang** [comment]
只要在最後預測時，丟入的data不要有包括model那一欄位
(因為僅該欄位有109筆是NA值)
出來的結果也不會筆數有少了

大概code如下:
Normalize_AllTestset_s<-subset(Normalize_AllTestset,select=-model)
pred_result2 <- predict(svm_tune2, Normalize_AllTestset_s)

**Comment by danahuang** [comment]
# SVM模型使用時，資料一定不能有NA值，否則預測結果會缺筆數
