### ISSUE TITLE
[Data Clean][建模] wush大大code討論區

### ISSUE THREAD

**Issue by luffy024688** [rladiestaipei/GoKaggleUsedCar#17]
[現況]希望可以站在巨人的肩膀上繼續訓練，看了wush大大的code覺得程式處理的很精簡，很值得學習！
但有一些不懂背後的含義，希望可以大家一起討論～～有wush大大親自解答就更好了ＸＤＤＤ

目前卡住的部分
[問題一]  binning funtion這段看不太懂    想問 **_binning function 的目的？_**   _**by = 0.25 /by=0.5是在做什麼？**_

binning <- function(x, breaks = NULL, by = 0.25) {
  if (is.null(breaks)) breaks <- quantile(x) %>% unique()
  result <- cut(x, breaks = breaks, include.lowest = TRUE)
  attr(result, "breaks") <- breaks
  result
}
binningCols <- c("yearOfRegistration", "powerPS", "kilometer", "ad_exist_time", posixCols)
binningCols <- c()
binningColsBy <- list(
  "powerPS" = 0.05
)
for(col in binningCols) {
  if (col %in% names(binningColsBy)) {
    by <- binningColsBy[[col]]
  } else {
    by <- 0.25
  }
  train[[col]] <- binning(train[[col]], by = by)
  test[[col]] <- binning(test[[col]], attr(train[[col]], "breaks"))
}

[問題二]**_為什麼會想把時間的格式轉成numeric的型態～_**

**Comment by luffy024688** [comment]
[問題三]   xgboost模型裡面 i 那行在做什麼?
m.train <- FeatureHashing::hashed.model.matrix(price ~ ., train, hash.size = 2^20)
m.test <- FeatureHashing::hashed.model.matrix(~ ., test, hash.size = 2^20)
**_i <- which((rep(1, nrow(m.train)) %*% m.train)@x >= 0)   #%*%:矩陣內積_**
m.train <- m.train[,i]
m.test <- m.test[,i]
data.train <- xgboost::xgb.DMatrix(m.train, label = train$price)

**Comment by wush978** [comment]
binning function 就是把數值型態（比例尺度或區間尺度）的資料轉換為類別型態（順序尺度），
類似把年齡切成0~9歲、10~19歲... 等區間的動作。

我實務經驗上，會希望每個區間的資料個數相同，所以這邊運用百分位數(quantile)的概念去切割, `by = 0.25`就是切割後每一組會有約25%的資料。

後面的程式碼只是要挑出哪些columns需要做binning。根據我後來跑cross validation的結果，我記得在這個問題上切binning沒什麼好處，預測效果反而變差。

**Comment by wush978** [comment]
> [問題二]為什麼會想把時間的格式轉成numeric的型態～

時間轉換成numeric的好處就是... 做binning比較簡單吧

**Comment by wush978** [comment]
> [問題三] xgboost模型裡面 i 那行在做什麼?

FeatureHashing之後會有一些column中所有資料都是0。
所以那行就是只挑出有1的column（怎麼挑？用線性代數運算），把全0的column刪除

**Comment by ClayLu** [comment]
不好意思，想請教關於[問題一]
binning 這個function的參數by = 0.25會在這個函數中的哪一行用到? 因為後來還會再遇到餵by =0.05到binning的狀況。看起來在函數中沒再看到"by"了 ? 

binning <- function(x, breaks = NULL, by = 0.25) {
 if (is.null(breaks)) breaks <- quantile(x) %>% unique()
 result <- cut(x, breaks = breaks, include.lowest = TRUE)
 attr(result, "breaks") <- breaks
 result
 }

**Comment by wush978** [comment]
唔，那段好像寫錯了，應該是要pass給quantile

**Comment by luffy024688** [comment]
[問題]  
#Feature Hashing 
m.train <- FeatureHashing::hashed.model.matrix(price ~ ., train, hash.size = 2^20)
m.test <- FeatureHashing::hashed.model.matrix(~ ., test, hash.size = 2^20)
i <- which((rep(1, nrow(m.train)) %*% m.train)@x >= 0)   
m.train <- m.train[,i]
m.test <- m.test[,i]
data.train <- xgboost::xgb.DMatrix(m.train, label = train$price)
#=====從這開始我就都看不懂了ＱＱ
result <- lapply(1:10, function(i) {
  params <- list(
    "objective" = "reg:linear",
    "max_depth" = rpois(1, 3) + 3,
    eta = runif(1, 0, 1),
    min_child_weight = rpois(1, 1) + 1,
    subsample = runif(1, 0.5, 1),
    colsample_bytree = runif(1, 0.5, 1),
    lambda = ifelse(runif(1, 0, 1) > 0.5, 0, rexp(1)),
    lambda_bias = ifelse(runif(1, 0, 1) > 0.5, 0, rexp(1))#,
    )
  g0 <- xgboost::xgb.cv(
    params = params,
    data = data.train,
    nrounds = 1000,
    nfold = 5,
    showsd = TRUE,
    early_stopping_rounds = 5,
    prediction = TRUE
    )
  g <- xgboost::xgb.train(
    params = params,
    data = data.train,
    nrounds = g0$best_iteration,
    )
  list(g = g, g0 = g0)
})

saveRDS(result, file = "result-try1.Rds")   #result2 <- readRDS("result-try1.Rds")

m2.train <- lapply(result, function(.) {
  .$g0$pred
}) %>%
  do.call(what = cbind)

m2.test <- lapply(result, function(.) {
  predict(.$g, m.test)
}) %>%
  do.call(what = cbind)

g2 <- lm(train$price ~ m2.train)
p2 <- m2.test %*% (g2$coef %>% tail(-1)) + g2$coef[1]

＃＃ g$best_iteration
submission <- data.table::fread("submit.csv")
submission$predict <- p2
＃＃＃readLines("submit.csv", n = 6)
write.csv(submission, file = "try1.csv", quote = FALSE, row.names = FALSE)

**Comment by wush978** [comment]
那些函數不懂?

**Comment by ClayLu** [comment]
1.不好意思，想請教關於[問題三]
i <- which((rep(1, nrow(m.train)) %*% m.train)@x >= 0)
我下str(i)得到:
 int [1:1048576] 1 2 3 4 5 6 7 8 9 10 ...
1048576似乎是m.train原來的欄位數量，如果要把全0的column刪除。是否可以這樣寫?
 which((rep(1, nrow(m.train)) %*% m.train)@x >= **1**)

2.關於後面的建模方式，我也寫寫自己看到的，如果有不對的再麻煩糾正我~~
我是覺得WUSH大大的code最後在預測的時候把模型分成兩階段。
第一階段:
用不同參數建立10個xgboost模型並產出xgboost預測值，而每個模型還有5個CV。
第二階段:
再把第一階段這10個模型結果的每一個都當成一個變數，把這些變數用lm找到每個變數(模型)權重。

就一筆資料來看。可以說生出10個預測值，並以適當權重將他們組合在一起當做最後預測值。

**Comment by f5130052** [comment]
```

library(magrittr)
train <- data.table::fread("trainset.csv")
test <- data.table::fread("testset.csv")
colnames(train)
posixCols <- c("dateCrawled", "dateCreated", "lastSeen")
for(col in posixCols) {
  train[[col]] <- strptime(train[[col]], "%Y-%m-%dT%H:%M:%SZ") %>% as.POSIXct()
  test[[col]] <- strptime(test[[col]], "%Y-%m-%dT%H:%M:%SZ") %>% as.POSIXct()
}
fakeIntCols <- c("monthOfRegistration", "postalCode")
for(col in fakeIntCols) {
  train[[col]] <- as.character(train[[col]])
  test[[col]] <- as.character(test[[col]])
}
binning <- function(x, breaks = NULL, by = 0.25) {
  if (is.null(breaks)) breaks <- quantile(x) %>% unique()
  result <- cut(x, breaks = breaks, include.lowest = TRUE)
  attr(result, "breaks") <- breaks
  result
}
invalidCols <- c("id", "nrOfPictures", "seller", "offerType")
for(col in invalidCols) {
  test[[col]] <- train[[col]] <- NULL
}
# binningCols <- c("yearOfRegistration", "powerPS", "kilometer", "ad_exist_time", posixCols)
binningCols <- c()
binningColsBy <- list(
  "powerPS" = 0.05
)
for(col in binningCols) {
  if (col %in% names(binningColsBy)) {
    by <- binningColsBy[[col]]
  } else {
    by <- 0.25
  }
  train[[col]] <- binning(train[[col]], by = by)
  test[[col]] <- binning(test[[col]], attr(train[[col]], "breaks"))
}
posixToNumericCols <- posixCols
for(col in posixToNumericCols) {
  train[[col]] <- as.numeric(train[[col]])
  test[[col]] <- as.numeric(test[[col]])
}
m.train <- FeatureHashing::hashed.model.matrix(price ~ ., train, hash.size = 2^20)
m.test <- FeatureHashing::hashed.model.matrix(~ ., test, hash.size = 2^20)
i <- which((rep(1, nrow(m.train)) %*% m.train)@x >= 0)
m.train <- m.train[,i]
m.test <- m.test[,i]
data.train <- xgboost::xgb.DMatrix(m.train, label = train$price)

result <- lapply(1:10, function(i) {
  params <- list(
    "objective" = "reg:linear",
    "max_depth" = rpois(1, 3) + 3,
    eta = runif(1, 0, 1),
    min_child_weight = rpois(1, 1) + 1,
    subsample = runif(1, 0.5, 1),
    colsample_bytree = runif(1, 0.5, 1),
    lambda = ifelse(runif(1, 0, 1) > 0.5, 0, rexp(1)),
    lambda_bias = ifelse(runif(1, 0, 1) > 0.5, 0, rexp(1))#,
    )
  g0 <- xgboost::xgb.cv(
    params = params,
    data = data.train,
    nrounds = 1000,
    nfold = 5,
    showsd = TRUE,
    early_stopping_rounds = 5,
    prediction = TRUE
    )
  g <- xgboost::xgb.train(
    params = params,
    data = data.train,
    nrounds = g0$best_iteration,
    )
  list(g = g, g0 = g0)
})

saveRDS(result, file = "result-try1.Rds")

m2.train <- lapply(result, function(.) {
  .$g0$pred
}) %>%
  do.call(what = cbind)
m2.test <- lapply(result, function(.) {
  predict(.$g, m.test)
}) %>%
  do.call(what = cbind)

g2 <- lm(train$price ~ m2.train)
p2 <- m2.test %*% (g2$coef %>% tail(-1)) + g2$coef[1]
# 
# # g$best_iteration
submission <- data.table::fread("submit.csv")
submission$predict <- p2
# # # readLines("submit.csv", n = 6)
write.csv(submission, file = "try1.csv", quote = FALSE, row.names = FALSE)


```

**Comment by luffy024688** [comment]
這個issue告一段落要關閉囉   感謝大家參與和峰哥的說明 特別感謝wush大大每次詳細的回答！～～
https://github.com/rladiestaipei/GoKaggleUsedCar/wiki/%5BData-Clean%5D%5B建模%5D-wush大大code

**Comment by wush978** [comment]
@ClayLu 

> which((rep(1, nrow(m.train)) %% m.train)@x >= 1)

你是對的，我原本寫的程式碼弄錯了，應該是要寫 `which((rep(1, nrow(m.train)) %% m.train)@x >= 1)`

> 2. ...(後略)

是的，這裡我是應用 [http://machine-learning.martinsewell.com/ensembles/stacking/n](http://machine-learning.martinsewell.com/ensembles/stacking/)的技術。實務上, CV非常非常重要，這裡的作法就給大家參考
