### ISSUE TITLE
7/23 會議記錄

### ISSUE THREAD

**Issue by ningchencontact** [rladiestaipei/GoKaggleUsedCar#20]
不好意思 今天用hangout 還有FB 群聊 都有遇到限制 不是很順，今天先停住，我們下次用room。

- 由於下次開會時間撞8/8，不確定大家是不是都行，臉書對話有開時間選擇，請大家投票

- 請大家填寫 你希望下次實體碰面 mentor來回答的issue
許願池....
@danahuang #10 [Data Clean][SVM]預測值筆數有少  
@Ning #2 [線性回歸] [資料探索] 如何知道資料集右偏或是左偏，並做相關調整 

- 請上次實體開會沒參加到，想要瞭解怎麼進行的人，私下ping我，我們在找時間一起討論

**Comment by angiehsu** [comment]
@angiehsu #13 [建模]xgboost
有看了一些文章跟sample code, 但對原理不是很理解
